### ISSUE TITLE
How to install your rainmeter skins?

### ISSUE THREAD

**Issue by Firefox289** [Blu3Jive001/Awesome-Windows#2]
Hey uhhm the rainmeter skins i just see ini files i can find any rmskin how do use these skins?

**Comment by Blu3Jive001** [comment]
This is in no way a suitable suite for anyone to seriously use. You need to individually drag each element to where it needs to go, and pretty much everything looks like it works but has no actual code behind it. You can install it by placing the rainmeter files in your Rainmeter skin files folder.
